"""empty message

Revision ID: 99d03497f921
Revises: 
Create Date: 2024-07-02 18:18:22.923032

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "99d03497f921"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("extension", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_files_category"), "files", ["category"], unique=False)
    op.create_index(op.f("ix_files_created_at"), "files", ["created_at"], unique=False)
    op.create_index(op.f("ix_files_extension"), "files", ["extension"], unique=False)
    op.create_index(op.f("ix_files_id"), "files", ["id"], unique=False)
    op.create_index(op.f("ix_files_updated_at"), "files", ["updated_at"], unique=False)
    op.create_table(
        "user_auth_codes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("auth_code", sa.String(), nullable=False),
        sa.Column("expired_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_auth_codes_auth_code"),
        "user_auth_codes",
        ["auth_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_auth_codes_created_at"),
        "user_auth_codes",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_auth_codes_email"), "user_auth_codes", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_user_auth_codes_id"), "user_auth_codes", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_user_auth_codes_status"), "user_auth_codes", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_user_auth_codes_updated_at"),
        "user_auth_codes",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("gender", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("resume_file_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("email"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(
        op.f("ix_users_phone_number"), "users", ["phone_number"], unique=False
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_index(op.f("ix_users_updated_at"), "users", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_updated_at"), table_name="users")
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_user_auth_codes_updated_at"), table_name="user_auth_codes")
    op.drop_index(op.f("ix_user_auth_codes_status"), table_name="user_auth_codes")
    op.drop_index(op.f("ix_user_auth_codes_id"), table_name="user_auth_codes")
    op.drop_index(op.f("ix_user_auth_codes_email"), table_name="user_auth_codes")
    op.drop_index(op.f("ix_user_auth_codes_created_at"), table_name="user_auth_codes")
    op.drop_index(op.f("ix_user_auth_codes_auth_code"), table_name="user_auth_codes")
    op.drop_table("user_auth_codes")
    op.drop_index(op.f("ix_files_updated_at"), table_name="files")
    op.drop_index(op.f("ix_files_id"), table_name="files")
    op.drop_index(op.f("ix_files_extension"), table_name="files")
    op.drop_index(op.f("ix_files_created_at"), table_name="files")
    op.drop_index(op.f("ix_files_category"), table_name="files")
    op.drop_table("files")
    # ### end Alembic commands ###
